config/routes.rb
Rails.application.routes.draw do
  resources :organisations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'invoices#index'
  
  resources :invoices
  get 'invoices/new', to: 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# == Schema Information
#
# Table name: organisations
#
#  id         :bigint           not null, primary key
#  name       :string
#  email      :string
#  address    :text
#  phone      :string
#  website    :string
#  logo_url   :string
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Client < Organisation
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id              :bigint           not null, primary key
#  invoice_number  :string
#  tnc             :text
#  notes           :text
#  due_date        :datetime
#  adjustments     :decimal(, )
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint
#  generation_date :datetime
#
class Invoice < ApplicationRecord
  has_many :items
  belongs_to :user

  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

  validates :invoice_number, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false }
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  amount      :decimal(, )
#  invoice_id  :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Item < ApplicationRecord
  belongs_to :invoice
end

app/models/organisation.rb
# == Schema Information
#
# Table name: organisations
#
#  id         :bigint           not null, primary key
#  name       :string
#  email      :string
#  address    :text
#  phone      :string
#  website    :string
#  logo_url   :string
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Organisation < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :invoices
end

app/models/vendor.rb
# == Schema Information
#
# Table name: organisations
#
#  id         :bigint           not null, primary key
#  name       :string
#  email      :string
#  address    :text
#  phone      :string
#  website    :string
#  logo_url   :string
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Vendor < Organisation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = current_user.invoices.new(invoice_params)
    # TODO: Add items as nested attributes
    if @invoice.save!
      redirect_to invoices_path
    end
  end

  def next_method
    binding.pry
  end

  private
  def invoice_params
    params.require(:invoice).permit(:invoice_number, :due_date, :generation_date, :tnc, items_attributes: [:id, :name, :description, :amount])
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[ show edit update destroy ]

  # GET /organisations or /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1 or /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations or /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to organisation_url(@organisation), notice: "Organisation was successfully created." }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1 or /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to organisation_url(@organisation), notice: "Organisation was successfully updated." }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1 or /organisations/1.json
  def destroy
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url, notice: "Organisation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organisation_params
      params.require(:organisation).permit(:name, :email, :address, :phone, :website, :logo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/invoices/_form.html.erb
<%= form_with model: @invoice do |f| %>
  <div class='field'>
		<%= f.text_field :invoice_number %>
		<%= f.label :invoice_number %><br>
	</div>
	
	<div class='field'>
		<%= f.date_field :due_date %>
		<%= f.label :due_date %><br>
	</div>

	<div class='field'>
		<%= f.date_field :generation_date %>
		<%= f.label :generation_date %><br>
	</div>

	<h3> Items</h3>
	<div id='items'>
    <%= f.fields_for :items do |item| %>
      <%= render 'item_fields', :f => item %>
    <% end %>
		
    <div class='links'>
      <%= link_to_add_association 'add item', f, :items %>
    </div><br>
  </div>
	<div class='field'>
		<%= f.text_area :notes %>
		<%= f.label :notes %>
	</div>
	<div class='field'>
		<%= f.text_area :tnc %>
		<%= f.label :tnc %>
	</div>
	<div>
		<%= f.submit %>
	</div>
<% end %>

app/views/invoices/_item_fields.html.erb
<div class='nested-fields'>
		<%= f.text_field :name, placeholder: 'Name' %>
		<%= f.text_field :description, placeholder: 'Description' %>
		<%= f.text_field :amount, placeholder: 'Amount' %>
	<%= link_to_remove_association "remove task", f %>
</div>

app/views/invoices/index.html.erb
<% if user_signed_in? %> 
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to "login", new_user_session_path %>
<% end %>
<%# <%= link_to 'Create Invoice', new_invoice_path %>  %>
<br />
----------------------------------Rails until here-----------------------------------

<div id="invoice-root" invoices="<%= @invoices.to_json %>"></div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>
 <%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceGenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.6.0.slim.min.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
    <%#= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organisations/_form.html.erb
<%= form_with(model: organisation, local: true) do |form| %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% organisation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="field">
    <%= form.label :logo_url %>
    <%= form.text_field :logo_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organisations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Logo url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
        <td><%= organisation.name %></td>
        <td><%= organisation.email %></td>
        <td><%= organisation.address %></td>
        <td><%= organisation.phone %></td>
        <td><%= organisation.website %></td>
        <td><%= organisation.logo_url %></td>
        <td><%= link_to 'Show', organisation %></td>
        <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organisation.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @organisation.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organisation.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @organisation.website %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @organisation.logo_url %>
</p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>